locators:
  - table
  - playerOne
  - playerTwo
  - playerThree
  - playerFour
  - playerFive
  - playerCards
  - playerUniqueCards
  - tableCards
  - playerBalance
  - cardTerminal
  - cardMall
  - cardAmusementPark
  - cardRadioTower
  - cardWheatField
  - cardFarm
  - cardBakery
  - cardCafe
  - cardShop
  - cardForest
  - cardBusinessCenter
  - cardTelevisionCenter
  - cardStadium
  - cardCheeseFactory
  - cardFurnitureFactory
  - cardMine
  - cardRestaurant
  - cardAppleOrchard
  - cardFruitMarket